### ISSUE TITLE
[Question] Documentation for Office tools

### ISSUE THREAD

**Issue by polderudo** [unidoc/unipdf-examples#68]
Is there any documentation for the office suite?

**Comment by gunnsth** [comment]
We are working on creating more documentation and more examples.

Currently we have:
- godoc: https://godoc.org/github.com/unidoc/unioffice 
- examples: https://github.com/unidoc/unioffice/tree/master/_examples
- our blog https://unidoc.io/news/
- this repository, both issues and code base.

If an example is missing, or you cannot find out how to do something.  We encourage everyone to create issues so that the proper examples can be created.

**Comment by gunnsth** [comment]
Note this repository is for UniPDF.  I.e. examples for UniPDF.  The examples for UniOffice are all under  https://github.com/unidoc/unioffice/tree/master/_examples
