### ISSUE TITLE
Cloud Providers

### ISSUE THREAD

**Issue by PmgFranco** [unidoc/unipdf-examples#89]
Hi,

I'm planning on using the license version in the future. I'm interested in the digital signatures functionality. 

However, I don't see examples for different cloud providers. Is it possible to add an example integrating with AWS KMS and Google Cloud KMS?

Tried the [external example](https://github.com/unidoc/unipdf-examples/blob/master/signatures/pdf_sign_external.go) but it seems it doesn't do the trick.

**Comment by gunnsth** [comment]
@PmgFranco Yes this is possible and used in production by some of our clients.  Can you clarify what the problem is?  Note that you need to make sure that you use a signature type that is supported by the PDF standard.
For Google KMS you should be able to use 3072 bit RSA key, PKCS#1 v1.5 padding - SHA256 digest. algorithm.
